doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        server_version: '16'
        types:
            brand_handle: App\ColorLab\Infrastructure\Doctrine\Type\BrandHandleType
            color_handle: App\ColorLab\Infrastructure\Doctrine\Type\ColorHandleType
            paint_type_handle: App\ColorLab\Infrastructure\Doctrine\Type\PaintTypeHandleType
            range_handle: App\ColorLab\Infrastructure\Doctrine\Type\RangeHandleType
            paint_reference_id: App\ColorLab\Infrastructure\Doctrine\Type\PaintReferenceIdType
            paint_reference_handle: App\ColorLab\Infrastructure\Doctrine\Type\PaintReferenceHandleType
            paint_id: App\ColorLab\Infrastructure\Doctrine\Type\PaintIdType
            range_collection: App\ColorLab\Infrastructure\Doctrine\Type\RangeCollectionType
            user_id: App\Shared\Infrastructure\Doctrine\Type\UserIdType

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            ColorLab:
                type: attribute
                dir: '%kernel.project_dir%/src/ColorLab/Domain'
                prefix: 'App\ColorLab\Domain'
                is_bundle: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
